version: 2

sources:
    - name: staging
      database: clear-router-390022
      schema: trips_data_all

      tables:
        - name: green_tripdata
        - name: yellow_tripdata
       
